
# This configuration has been generated by the Azure Terraform plugin which utilizes Generative AI which may result in unintended or inaccurate configuration code. A human must validate that this configuration accomplishes the desired goal before applying the configuration.

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "tfex-example-rg"
  location = "West Europe"
}

resource "azurerm_automation_account" "example" {
  name                = "tfex-example-account"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku_name            = "Basic"
}

resource "azurerm_automation_variable_bool" "example" {
  name                    = "tfex-example-var-bool"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  value                   = false
  encrypted               = true
}

resource "azurerm_automation_variable_string" "example" {
  name                    = "tfex-example-var-string"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  value                   = "Hello, Terraform"
  encrypted               = true
}

resource "azurerm_automation_variable_int" "example" {
  name                    = "tfex-example-var-int"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  value                   = 1234
  encrypted               = true
}

resource "azurerm_automation_variable_datetime" "example" {
  name                    = "tfex-example-var-datetime"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  value                   = "2023-10-01T00:00:00Z"
  encrypted               = true
}
