
# This configuration has been generated by the Azure Terraform plugin which utilizes Generative AI which may result in unintended or inaccurate configuration code. A human must validate that this configuration accomplishes the desired goal before applying the configuration.

provider "azurerm" {
  features {}
}

resource "azurerm_security_center_subscription_pricing" "keyvault_pricing" {
  tier          = "Standard"
  resource_type = "KeyVaults"
}
