
# This configuration has been generated by the Azure Terraform plugin which utilizes Generative AI which may result in unintended or inaccurate configuration code. A human must validate that this configuration accomplishes the desired goal before applying the configuration.

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resource-group"
  location = "West Europe"
}

resource "azurerm_cosmosdb_account" "example" {
  name                  = "example-cosmos-db"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name
  offer_type            = "Standard"
  kind                  = "GlobalDocumentDB"
  public_network_access_enabled = false
  is_virtual_network_filter_enabled = true

  geo_location {
    location          = "eastus"
    failover_priority = 0
  }

  virtual_network_rule {
    id = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworks/{virtualNetworkName}/subnets/{subnetName}"
  }

  ip_range_filter = ["10.0.0.0/24"]

  consistency_policy {
    consistency_level = "Session"
  }
}
