
# This configuration has been generated by the Azure Terraform plugin which utilizes Generative AI which may result in unintended or inaccurate configuration code. A human must validate that this configuration accomplishes the desired goal before applying the configuration.

provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "East US"
}

resource "azurerm_key_vault_managed_hardware_security_module" "example" {
  name                     = "example-hsm"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  sku_name                 = "Standard_B1"
  tenant_id                = data.azurerm_client_config.current.tenant_id
  admin_object_ids         = [data.azurerm_client_config.current.object_id]
  purge_protection_enabled = false
}

resource "azurerm_key_vault_managed_hardware_security_module_key" "example" {
  name           = "example-key"
  managed_hsm_id = azurerm_key_vault_managed_hardware_security_module.example.id
  key_type       = "RSA-HSM"
  key_size       = 2048
  key_opts       = ["encrypt", "decrypt", "sign"]

  depends_on = [
    azurerm_key_vault_managed_hardware_security_module.example
  ]
}
