
# This configuration has been generated by the Azure Terraform plugin which utilizes Generative AI which may result in unintended or inaccurate configuration code. A human must validate that this configuration accomplishes the desired goal before applying the configuration.

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_mysql_server" "example" {
  name                         = "example-mysql-server"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  version                      = "5.7"
  administrator_login          = "mysqladmin"
  administrator_login_password = "AdminPassword123!"
  sku {
    name     = "B_Gen5_1"
    tier     = "Basic"
    capacity = 1
  }
  public_network_access_enabled = false
}
