
# This configuration has been generated by the Azure Terraform plugin which utilizes Generative AI which may result in unintended or inaccurate configuration code. A human must validate that this configuration accomplishes the desired goal before applying the configuration.

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "examplestoracc"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"

  queue_properties {
    cors_rule {
      allowed_origins = ["*"]
      allowed_methods = ["GET", "POST"]
      max_age_in_seconds = 3600
      exposed_headers = ["*"]  # Updated to meet minimum item requirement
      allowed_headers = ["*"]   # Updated to meet minimum item requirement
    }

    logging {
      version               = "1.0"
      delete                = true
      read                  = true
      write                 = true
      retention_policy_days = 7
    }

    hour_metrics {
      version               = "1.0"
      enabled               = true  # Added required field
      retention_policy_days = 7
    }

    minute_metrics {
      version               = "1.0"
      enabled               = true  # Added required field
      retention_policy_days = 7
    }
  }
}
